name: example
description: Example
version: 2.3.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  selectable_autolink_text:
    path: ../../flutter_selectable_autolink_text
  url_launcher: ^6.0.2
  share: ^2.0.4

flutter:
  uses-material-design: true
