name: example
description: Example
version: 1.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  selectable_autolink_text:
    path: ../../flutter_selectable_autolink_text
  url_launcher: ^5.2.5
  share: ^0.6.3+1

flutter:
  uses-material-design: true
