name: example
description: Example
version: 1.3.4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  selectable_autolink_text:
    path: ../../flutter_selectable_autolink_text
  url_launcher: ^5.4.10
  share: ^0.6.4+3

flutter:
  uses-material-design: true
