name: selectable_autolink_text
description: Generate inline links that can be selected and tapped in text for Flutter.
version: 1.3.4
homepage: https://github.com/miyakeryo/flutter_selectable_autolink_text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
